### ISSUE TITLE
Refactor scheduled_activity endpoint route

### ISSUE THREAD

**Issue by dylanconnolly** [M4-Cross-Poll/backend#28]
Refactor endpoint for a scheduled_activity show page to be '/api/v1/users/:user_id/scheduled_activities/:scheduled_activity_id'

**Comment by darren2802** [comment]
how come we don't have users before :user_id?

**Comment by dylanconnolly** [comment]
as in '/api/v1/users/:user_id/scheduled_activities/:scheduled_activity_id'? Not sure, I suppose that would be more RESTful right?

**Comment by darren2802** [comment]
Yeah just seems a bit strange to have a resource id as the first uri segment
